### ISSUE TITLE
Javac cannot find symbols com.facebook.react.uimanager.BaseViewPropertyApplicator, com.facebook.react.uimanager.CatalystStylesDiffMap

### ISSUE THREAD

**Issue by GeoffreyPlitt** [sejoker/react-native-android-vitamio#10]
Hello,

I've rnpm-installed this component in my React app, and modified various files based on the Demo app example you've provided. But my java compilation step is failing:

RNVitamioView:compileReleaseJavaWithJavac
/Users/webfreelance10/eaplay_good/node_modules/react-native-android-vitamio/src/main/java/com/RNVitamioView/VitamioViewManager.java:8: error: cannot find symbol
import com.facebook.react.uimanager.BaseViewPropertyApplicator;
                                   ^
  symbol:   class BaseViewPropertyApplicator
  location: package com.facebook.react.uimanager
/Users/webfreelance10/eaplay_good/node_modules/react-native-android-vitamio/src/main/java/com/RNVitamioView/VitamioViewManager.java:9: error: cannot find symbol
import com.facebook.react.uimanager.CatalystStylesDiffMap;
                                   ^
  symbol:   class CatalystStylesDiffMap
  location: package com.facebook.react.uimanager
2 errors
:RNVitamioView:compileReleaseJavaWithJavac FAILED

Here are my versions of React:
$ react-native --version
react-native-cli: 0.2.0
react-native: 0.26.2

Please advise, thanks.

**Comment by sejoker** [comment]
@GeoffreyPlitt I hope I will have enough courage continue upgrade my library to the latest RN. At the moment, it works with RN up to 0.21. Every release of RN requires code changes, it is frustrating, but this is the reality https://twitter.com/sejoker/status/732287557048926208

**Comment by GeoffreyPlitt** [comment]
I sympathize! If you have some tips on how to fix it, I might be able to
help and send you a PR

On Sun, May 29, 2016 at 5:25 AM, Yevgen Safronov notifications@github.com
wrote:

> @GeoffreyPlitt https://github.com/GeoffreyPlitt I hope I will have
> enough courage continue upgrade my library to the latest RN. At the moment,
> it works with RN up to 0.21. Every release of RN requires code changes, it
> is frustrating, but this is the reality
> https://twitter.com/sejoker/status/732287557048926208
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/sejoker/react-native-android-vitamio/issues/10#issuecomment-222357915,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAXXZQHRTFi9ku_ebit8Pb8OhzdhJ6z5ks5qGYWzgaJpZM4Io4ur
> .

## 

http://www.geoffplitt.com
http://facebook.com/geoffrey.plitt
https://twitter.com/GeoffreyPlitt
773.339.0915

**Comment by shaunhaney** [comment]
Any future work planned on react-native-android-vitamio?  I tried running the sample program and it looks like this component will work for me, thus I am going to see if I can bring it up to a more current React-Native version.  I am new to both React-Native and Android, so this might take a bit.

**Comment by wilbyang** [comment]
@GeoffreyPlitt I have the same issue. have you resolved this?

**Comment by GeoffreyPlitt** [comment]
Nope, this package isn't maintained. I suggest https://github.com/react-native-community/react-native-video
